apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: demo-config
  source:
    path: 01-admins/overlays/01-cicd-admin-config
    repoURL: https://github.com/timhansendev/99-gitops-demo.git
    targetRevision: development
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
